### ISSUE TITLE
readme on npm does not match the one on github

### ISSUE THREAD

**Issue by revelt** [rollup/rollup-plugin-strip#11]
hi guys,

NPM readme on https://www.npmjs.com/package/rollup-plugin-strip is different from the GitHub's. Let's do something about it. Maybe it's because of capitalisation of the readme file name??

**Comment by kalitine** [comment]
For me the NPM page says: "No readme found!". It looks like an NPM [issue](https://github.com/npm/registry/issues/118) which for some is resolved after the package was republished.

Anyway in order to have the same README file, a new version has to be published (no problem with capitalisation). Because the current README file is the one from [v1.1.1 release](https://github.com/rollup/rollup-plugin-strip/tree/v1.1.1).

**Comment by revelt** [comment]
Looks sorted now. Thanks guys! Closing.
